### PR TITLE
Fix gsm config view

### PR DESCRIPTION
**Pull request by Yacubane**

### CODE REVIEW

**Review by franczakr — APPROVED** [review]
OK

**Comment by piaskowyk** [comment]
Good job @jakubdybczak and @franczakr I really need this changes!

**Comment by franczakr** [comment]
@piaskowyk, you can download latest version here: https://github.com/airella-system/airella-android-app/releases/tag/v3.5

**Comment by piaskowyk** [comment]
You are awesome guys! I use this app to configuration my own air sensor, this app is really helpful for configure this.

**Pull request merged**
